nics:
  eth1:  # ifname
    # qos-map
    _tas:
      schedule:
        - time: 300us
          prio: [ 5 ]
        - time: 300000ns
          prio: [ 2, 3 ]
        - time: 400000
          prio: [ -1 ]
    _cbs:
      # prio: dict map
      3:
        class: a
        max_frame: 512B
        bandwidth: 70000kbps
      2:
        class: b
        max_frame: 512B
        bandwidth: 30Mbps
